-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgpCTfTD6WVkCowOTW
TWxTjM6VTdRIwX+85AJyMfhUtXCgCgYIKoZIzj0DAQehRANCAATvPd5WGSwInaEf
Gue3p0SIaHijsP+wwDEAjQvPbJ/7R8PM0IWNgBoNixuKMa/Iy29kg7S/F0gMBMiB
FezVpYOd
-----END PRIVATE KEY-----